apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260508-014615-643qx4nslsc6-service
spec:
  selector:
    app: enterprise-system-20260508-014615-643qx4nslsc6
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
